version: "3"

env:
  SERVICE_NAME: "trading-results-rs"
  DEV_LOCAL_TAG: "dev-env"

tasks:
  build-docker-local:
    cmds:
      - docker build -t "$SERVICE_NAME:$DEV_LOCAL_TAG" .

  run-docker-local:
    deps: [build-docker-local]
    cmds:
      - docker run --rm -t "$SERVICE_NAME:$DEV_LOCAL_TAG"

  run-docker-local-shell:
    cmds:
      - docker run --rm -it --entrypoint /bin/bash "$SERVICE_NAME:$DEV_LOCAL_TAG"

  start-db:
    cmds:
      - docker run --rm --name postgres -p 5432:5432 -e POSTGRES_DB=postgres -e POSTGRES_USER=superuser -e POSTGRES_PASSWORD=complicated postgres:15.7-alpine

  restore-db:
    cmds:
      - pg_restore --no-owner -h localhost -U superuser -d postgres db-dumps/trading-results-prod-2024-10-15.dump

  psql-shell:
    cmds:
      - psql -h localhost -U superuser postgres
